decoded:
    cache:
        port: ${REDIS_PORT}
        host: ${REDIS_HOST}
        password: ${REDIS_PASSWORD}

spring:
    data:
        mongodb:
            uri: ${DB_URI}
            database: ${DB}

withdraw:
    message:
        success: Your Withdrawal of N%d is successful you balance is N
        fail: inSufficient Balance N
