decoded:
    cache:
        port: 7186
        host: containers-us-west-44.railway.app
        password: KANkYPy0qh4LNGt50SKE
        default-ttl: 180

spring:
    data:
        mongodb:
            uri: ${DB_URI}
            database: ${DB}